
spring.application.name=hamburgueria

# Banco de dados MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/hamburgueria
spring.datasource.username=root
spring.datasource.password= josedev
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate — cria/atualiza as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Porta do servidor
server.port=8080